# Copyright (c) 2026 Microchip Technology Inc.
# SPDX-License-Identifier: Apache-2.0

# West manifest file for Microchip ZSDK for Zephyr.

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: microchip
      url-base: https://github.com/Zephyr4Microchip

  projects:
    - name: zephyr
      # Zephyr is fetched from the following remote and revision.
      remote: microchip
      repo-path: microchip-zephyr
      revision: cce0303a66215c0139515092339a7b166554a9ee
      import:
        # These modules are imported from west.yml in Zephyr repository.
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - cmsis_6
          - fatfs
          - littlefs
          - lvgl
          - mcuboot
          - mbedtls
          - picolibc
          - segger
          - tf-psa-crypto
          - zcbor
          - hal_atmel
    # Modules in zephyr repository west.yml but excluded from the name-allowlist are defined here.
    - name: hal_microchip
      # Overrides hal_microchip from Zephyr's west.yml with Microchip's version.
      remote: microchip
      repo-path: microchip-hal
      revision: 8c1cfb8c736faef1a4097ce9e32909f0d87f768a
      path: modules/hal/microchip
  self:
    path: microchip-zsdk
    # Configure west extensions.
    #west-commands: scripts/west-commands.yml
